---
title: "Running the DEXSeq model with using the statmod GLM fitter."
author: "Alejandro Reyes"
date: "`r BiocStyle::doc_date()`"
package: "`r BiocStyle::pkg_ver('DEXSeq')`"
abstract: >
  This package provides the DEXSeq methodology in an alternative
  implementation, using the GLM fitter from the statmod package
  and skipping the step of sharing information across exons. Its
  use is recommended only when a large number of biological
  replicates are available.
output:
  rmarkdown::html_document:
    highlight: pygments
    toc: true
    fig_width: 5
bibliography: 
vignette: >
  %\VignetteIndexEntry{DEXSeq alternative implementation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding[utf8]{inputenc}
---


<!-- This is the source document -->


```{r setup, echo=FALSE, results="hide"}
knitr::opts_chunk$set(tidy=FALSE, cache=TRUE,
                      dev="png",
                      message=FALSE, error=FALSE, warning=TRUE)
```

The code chunk below demonstrates the workflow. The data used
to demonstrate this workflow is the pasilla dataset.

```{r workflow}
library(DEXSeqAlt)
data("pasillaDEXSeqDataSet", package="pasilla")

reducedModel <- ~ sample + exon
fullModel <- ~ sample + exon + condition:exon
design(dxd) <- fullModel

dxd <- estimateSizeFactors( dxd )
dxd <- estimateDispersionsAlt( dxd, verbose=FALSE )
dxd <- testForDEUAlt(dxd, reducedModel=reducedModel, fullModel=fullModel, verbose=FALSE )


```

The p-values and q-values can be found the following slot of the DEXSeqDataSet object

```{r results}
mcols(dxd)
```


```{r sessionInfo}
sessionInfo()
```

